### PR TITLE
Fix prefixlists

### LINKED ISSUE #115: spec test are failing
at the develop branch spec test are falling, testet commit 61f9dad01caa622c1d99f9ffc6d875c41ea4cd32
```
Failures:

  1) Puppet::Type::Eos_prefixlist::ProviderEos instance methods #create extracts seqno and prefix_list from name
     Failure/Error: new_resource.provider.flush
       Double "prefixlists" received unexpected message :add_rule with ("test99", :permit, "10.99.0.0/16", 99)
     # ./lib/puppet/provider/eos_prefixlist/default.rb:143:in `flush'
     # ./spec/unit/puppet/provider/eos_prefixlist/default_spec.rb:218:in `block (4 levels) in <top (required)>'

Finished in 1.78 seconds (files took 3.44 seconds to load)
2779 examples, 1 failure
```

### PR DESCRIPTION
**Pull request by jerearista**
- Fix #115 failing spec test
- Make several mocks in prefixlist more specific
- Resolve some rubocop findings.

### CODE REVIEW

File: spec/unit/puppet/provider/eos_prefixlist/default_spec.rb [hunk 1]
```diff
@@ -201,8 +201,8 @@ def prefixlists
 
       let(:new_resource) do
         resource_hash = {
-          ensure: :present,
           name: 'test99:99',
+          ensure: :present,
```
Comment (devrobo) [inline spec/unit/puppet/provider/eos_prefixlist/default_spec.rb]: Is moving this line required?

Comment (jerearista) [inline spec/unit/puppet/provider/eos_prefixlist/default_spec.rb]: No.  I will reset its position
